### ISSUE TITLE
After cloning, what should be the next step?

### ISSUE THREAD

**Issue by luckystar2794** [vinaysomawat/vinaysomawat.github.io#13]

**Comment by guilyx** [comment]
Hey @luckystar0409

1. `Fork`
2. Rename your repo `luckystar0409.github.io`
3. Activate github pages in `settings/GithubPages` by sourcing the targeted branch. Default : `master`
4. You can modify the .html files to suit your profile and model it after your information.

**Comment by guilyx** [comment]
@vinaysomawat  it's true that the readme only states that one should fork the remote and clone it, but this will only set you up to contribute, not actually set your own github pages website. I could clarify the readme with a PR ?

**Comment by vinaysomawat** [comment]
@Guilyx Yes, you're right. the readme only states just to contribute to this project not actually set their own Github pages. Please go ahead and update the readme to your fork and raise a pull request for the same.

**Comment by luckystar2794** [comment]
awesome thanks
