### ISSUE TITLE
[Feature] Github Calendar

### ISSUE THREAD

**Issue by guilyx** [vinaysomawat/vinaysomawat.github.io#16]
Hey @vinaysomawat 

I embedded the github calendar on my portfolio ( with your template as a basis ), I'd be happy to add it to the template if you'd like.

It's from Bloggify, same as the Pie Chart.

![githubpart](https://user-images.githubusercontent.com/43545812/81064600-416e8c00-8eda-11ea-9f24-f7bf144460ca.png)

**Comment by vinaysomawat** [comment]
@guilyx Yes, Done! Thanks.
