### ISSUE TITLE
sidebar color not changes in mobile view.

### ISSUE THREAD

**Issue by vinaysomawat** [vinaysomawat/vinaysomawat.github.io#2]
In desktop view, the background color of the sidebar is orange but in mobile view, it changes.

**Comment by mdvsh** [comment]
**"Can I work on this ?"**

**Comment by vinaysomawat** [comment]
Yes, fork the repository and do.

**Comment by b-rudo** [comment]
^ Please ignore.  Accidental referencing of issue
