### ISSUE TITLE
No Icons in Social Profiles only links

### ISSUE THREAD

**Issue by tarun-preet** [vinaysomawat/vinaysomawat.github.io#20]
On your Competitive Programming page, there's a Social Profiles section on which when you move your cursor over, it shows a link but there is no image, I'm using Windows 10, Chrome. Here's the image:
![image](https://user-images.githubusercontent.com/63860314/97453437-be476380-195b-11eb-9d74-edf905cb5e3e.png)

**Comment by thevinaysomawat** [comment]
Social Profile has been removed.
