### ISSUE TITLE
Have a page navigation tag

### ISSUE THREAD

**Issue by nautatva** [vinaysomawat/vinaysomawat.github.io#23]
**Is your feature request related to a problem? Please describe.**
https://vinaysomawat.github.io/#experience should open up the experience section. Helps in sharing relevant parts of the website easily.

**Describe the solution you'd like**
One thing that needs to be kept in mind is the 'back button' functionality should not be affected. Moving from one section to another should purely be a JS thing, else you might end up frustrating the user when he tries to go back.

**Comment by thevinaysomawat** [comment]
Removed other pages and added all pages content on the home page itself.
