### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Sanjana-027** [vinaysomawat/vinaysomawat.github.io#31]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hii, your portfolio is great , but , if you add a toggle button. I will look so nice.

**Comment by thevinaysomawat** [comment]
Hi Sajana, May you please explain toggle button of what?

**Comment by Sanjana-027** [comment]
Hii Vinay,
Your Portfolio is great. If you add toggle button to your website. It will
look so nice.
Toggle button:- It allows the user to change a setting between two states.
If you want to change your website into dark and whatever mode you want to
use just by clicking one button,this toggle button help you.

Don't worry, this button  will also keep your current background theme as
it look.

If you want I will do this for you.
I will generate a pull -request for this.

Thanks a lot for your response.


Thanking you.
Regards,
Sanjana Singh.

**Comment by thevinaysomawat** [comment]
Hi Sanjana, 

Please go ahead! That would be a great enhancement to this.

Thanks.

**Comment by Sanjana-027** [comment]
Hii Vinay,
Thank you so much for this.
Soon I will do this work.
Soon I will generate a pull request for you.

Thanking you.
Regrads
Sanjana Singh.

**Comment by vinaysomawat** [comment]
Added dark mode enhancement. Closing the issue for the same.
