### ISSUE TITLE
"My Projects" Overlapping in About sidebar (mobile view)

### ISSUE THREAD

**Issue by mdvsh** [vinaysomawat/vinaysomawat.github.io#5]
**"My Projects" Overlapping in About sidebar**
In mobile view of 
`https://vinaysomawat.github.io/`

This may also be a result of a misplaced `<div>` or omission of a `<br>` tag. It seems that the sidebar content `<div>` has been bugged.

I, being an experienced web developer (since grade6) would be able to debug these out to make this wonderful portfolio website great again.

![img-0955](https://user-images.githubusercontent.com/33770878/52160026-0e37be80-26d3-11e9-896f-18784d399a50.PNG)

**Comment by vinaysomawat** [comment]
Fixed.
